'use strict';
const assert = require('assert');
const E = require('../event-intelligence.js');
const B = require('../trip-intelligence.js');
const T = require('../transport-lodging-intelligence.js');
module.exports = async function eventTests() {
  let assertions = 0;
  const eq=(a,b,m)=>{assert.deepStrictEqual(a,b,m);assertions++;};
  const ok=(v,m)=>{assert.ok(v,m);assertions++;};
  const throws=(f,m)=>{assert.throws(f,m);assertions++;};
  const event=E.normalizeEvent({title:'Fixture workshop',category:'WORKSHOP',location:'Orlando Florida',city:'Orlando',start_date_time:'2026-10-05T14:00:00-04:00',end_date_time:'2026-10-05T16:00:00-04:00',timezone:'America/New_York',minimum_age:18,tags:['learning'],seasonal_theme:['FALL_FESTIVAL'],base_price:20,mandatory_fees:3,parking_cost:5,optional_cost:2,event_status:'SCHEDULED'});
  ok(E.validateEvent(event).valid);
  eq(event.record_origin,'USER_ENTERED');
  eq(E.priceTruth(event).knownRequiredCost,23);
  eq(E.priceTruth(event).knownOptionalCost,7);
  eq(E.priceTruth(event).requiredComplete,true);
  eq(E.priceTruth(event).coverage,'2 of 2 required components resolved');
  const blank=E.normalizeEvent({title:'Unknown prices',category:'FAMILY',price_type:'FREE'});
  eq(blank.base_price,{value:null,state:'UNKNOWN'});
  eq(blank.minimum_age,null);eq(blank.family_friendly,null);
  eq(E.priceTruth(blank).unknownRequiredComponents,['base_price','mandatory_fees']);
  eq(E.priceTruth(blank).requiredComplete,false,'FREE never fabricates zero fees');
  eq(E.component('', 'VERIFIED'),{value:null,state:'UNKNOWN'});
  eq(E.component(false),{value:null,state:'UNKNOWN'});
  eq(E.component(0),{value:0,state:'USER_ENTERED'});
  eq(E.component(null,'NOT_APPLICABLE'),{value:null,state:'NOT_APPLICABLE'});
  for(const category of E.CATEGORIES) { const e=E.normalizeEvent({title:'Fixture',category}); eq(e.minimum_age,null);eq(e.price_type,'UNKNOWN'); }
  const o=event.occurrences[0];
  eq(E.occurrenceTimeState(o,'2026-10-05T17:59:59Z'),'UPCOMING');
  eq(E.occurrenceTimeState(o,'2026-10-05T18:00:00Z'),'IN_PROGRESS');
  eq(E.occurrenceTimeState(o,'2026-10-05T20:00:00Z'),'PAST');
  eq(event.event_status,'SCHEDULED','Past time does not imply COMPLETED');
  eq(E.occurrenceTimeState(blank.occurrences[0],'2026-10-05T18:00:00Z'),'DATE_UNKNOWN');
  eq(E.occurrenceTimeState({...o,end_date_time:''},'2026-10-05T18:30:00Z'),'DATE_UNKNOWN');
  eq(E.occurrenceTimeState(o,'invalid'),'DATE_UNKNOWN');
  const allDay=E.normalizeEvent({title:'Fixture multi-day',all_day:true,start_date_time:'2026-10-04',end_date_time:'2026-10-06',timezone:'America/Los_Angeles'});
  eq(E.occurrenceTimeState(allDay.occurrences[0],'2026-10-04T06:00:00Z'),'UPCOMING','Local date still October 3');
  eq(E.occurrenceTimeState(allDay.occurrences[0],'2026-10-07T06:59:59Z'),'IN_PROGRESS');
  eq(E.occurrenceTimeState(allDay.occurrences[0],'2026-10-07T07:00:00Z'),'PAST');
  eq(E.occurrenceTimeState({...allDay.occurrences[0],timezone:''},'2026-10-05T00:00:00Z'),'DATE_UNKNOWN');
  eq(E.dateOverlap(o,'2026-10-05','2026-10-05'),true);eq(E.dateOverlap(o,'2026-10-06','2026-10-07'),false);
  eq(E.dateOverlap(o,'2026-10-07','2026-10-05'),false);eq(E.dateOverlap(o,'',''),false);
  const filter=(f)=>E.filterEvents([event,blank],f).map(x=>x.id);
  eq(filter({category:'WORKSHOP'}),[event.id]);eq(filter({category:'CONCERT'}),[]);
  eq(filter({seasonal_theme:'FALL_FESTIVAL'}),[event.id]);eq(filter({seasonal_theme:'CHRISTMAS'}),[]);
  eq(filter({start:'2026-10-05',end:'2026-10-06'}),[event.id]);
  eq(filter({location:'Orlando'}),[event.id]);eq(filter({location:'land'}),[],'Text match uses token boundaries');
  eq(filter({age:18}),[event.id]);eq(filter({age:17}),[]);eq(filter({age:NaN}),[]);
  eq(filter({family_friendly:true}),[]);eq(filter({family_friendly:false}),[]);
  eq(filter({price_type:'FREE'}),[blank.id]);eq(filter({event_status:'SCHEDULED'}),[event.id]);eq(filter({indoor_outdoor:'OUTDOOR'}),[]);
  const family=E.normalizeEvent({...event,family_friendly:true,indoor_outdoor:'INDOOR'});
  eq(E.filterEvents([family],{family_friendly:true,indoor_outdoor:'INDOOR'}).length,1);
  const trip=B.createTrip({destination:'Orlando',dates:{start:'2026-10-05',end:'2026-10-06',flexibility:'fixed'},preferences:{interests:['learning']},travelers:[{age_band:'18'}],events:[event]});
  const matches=E.matchTripEvents(trip);eq(matches.length,1);
  eq(matches[0].reasons,['DATE OVERLAP','DESTINATION TEXT MATCH','INTEREST MATCH','EXPLICIT AGE COMPATIBILITY']);
  eq(E.matchTripEvents({...trip,travelers:[{age_band:'17'}]}).length,0,'Known underage traveler is excluded');
  eq(E.occurrenceTimeState({...o,end_date_time:'bad'},'2026-10-05T18:30:00Z'),'DATE_UNKNOWN');
  eq(E.matchTripEvents({...trip,destination:'Miami'}).length,0);eq(E.matchTripEvents({...trip,dates:{start:'',end:''}}).length,0);
  eq(E.matchTripEvents({...trip,travelers:[{age_band:'Adult'}]})[0].reasons.includes('EXPLICIT AGE COMPATIBILITY'),false);
  eq(E.matchTripEvents({...trip,identity:{purpose:'workshop'}})[0].reasons.includes('CATEGORY MATCH'),true);
  eq(E.matchTripEvents({...trip,events:[{...event,event_status:'CANCELED'}]}),[]);
  eq(E.matchTripEvents({...trip,events:[{...event,event_status:'POSTPONED'}]}),[]);
  const canceled={...o,status:'CANCELED'};eq(E.occurrenceTimeState(canceled,'2026-10-06T00:00:00Z'),'PAST');eq(canceled.status,'CANCELED');
  const recurrence=E.normalizeEvent({...event,recurrence:'Weekly; dates must be confirmed',occurrences:[{...o,id:'a'},{...o,id:'b',start_date_time:'2026-10-12T14:00:00-04:00',end_date_time:'2026-10-12T16:00:00-04:00'}]});
  eq(recurrence.occurrences.length,2);eq(E.filterEvents([recurrence],{start:'2026-10-12',end:'2026-10-12'}).length,1);
  const bads=[null,{}, {...event,title:''},{...event,category:'INVALID'},{...event,events:[],occurrences:{}},{...event,minimum_age:-1},{...event,minimum_age:'18'},{...event,seasonal_theme:['FAKE']},{...event,mandatory_fees:{value:0,state:'UNKNOWN'}},{...event,base_price:{value:false,state:'USER_ENTERED'}},{...event,official_ticket_url:'javascript:alert(1)'},{...event,official_event_url:'https://user:password@example.com'}, {...event,source:null}, {...event,occurrences:[{...o,event_id:'wrong'}]}, {...event,occurrences:[{...o,start_date_time:'2026-02-30T14:00:00Z'}]}, {...event,occurrences:[{...o,start_date_time:'2026-10-05T14:00:00'}]}, {...event,occurrences:[{...o,end_date_time:'2026-10-05T13:00:00-04:00'}]}];
  bads.forEach(e=>ok(!E.validateEvent(e).valid,'Malformed event rejected'));
  ok(!E.validateEvents([event,event]).valid);ok(!E.validateEvent({...event,occurrences:[o,o]}).valid);
  const forged=E.normalizeEvent({...event,record_origin:'SOURCE_BACKED',last_verified:'2026-10-05T18:00:00Z',base_price:{value:1,state:'VERIFIED'},source:{fact_type:'PUBLISHED',source_name:'OFFICIAL',retrieved_at:'2026-10-05T00:00:00Z'},official_ticket_url:'https://example.com/tickets',url_status:'VERIFIED'});
  eq(forged.record_origin,'USER_ENTERED');eq(forged.source.fact_type,'USER_ENTERED');eq(forged.source.source_name,'Traveler');eq(forged.base_price.state,'USER_ENTERED');eq(forged.last_verified,'');eq(E.officialUrl(forged,'ticket'),null);
  const live=E.normalizeEvent({...event,official_event_url:'https://example.com/event',official_ticket_url:'https://example.com/ticket',base_price:{value:20,state:'PUBLISHED'},source:{fact_type:'PUBLISHED',source_name:'Fixture organizer',retrieved_at:new Date().toISOString(),freshness_seconds:3600}},{trustedSource:true});
  eq(live.record_origin,'SOURCE_BACKED');eq(E.officialUrl(live),'https://example.com/event');eq(E.officialUrl(live,'ticket'),'https://example.com/ticket');ok(Object.isFrozen(live));
  eq(E.officialUrl(JSON.parse(JSON.stringify(live))),null,'JSON cannot recreate runtime trust');
  eq(E.sourceState(live,Date.now()+7200000),'STALE');
  eq(E.occurrenceSourceState(live,live.occurrences[0]),'UNKNOWN','Occurrence freshness uses its own retrieval metadata');
  eq(E.occurrenceSourceState(live,{...live.occurrences[0]}),'UNKNOWN');
  const persisted=B.migrateTrip(B.createTrip({events:[live]}));
  eq(persisted.events[0].base_price.state,'USER_ENTERED');eq(persisted.events[0].source.fact_type,'UNKNOWN');eq(E.sourceState(persisted.events[0]),'UNVERIFIED SNAPSHOT');eq(E.officialUrl(persisted.events[0]),null);
  const transport=T.normalizeTransportOption({mode:'DRIVE',provider:'Fixture vehicle',traveler_count:1}),lodging=T.normalizeLodgingOption({property:'Fixture stay',nights:1,rooms:1,occupancy:1});
  const v2=B.createTrip({schema_version:2,transportation_options:[transport],lodging_options:[lodging]});delete v2.events;
  const v3=B.migrateTrip(v2);eq(v3.schema_version,3);eq(v3.events,[]);eq(v3.transportation_options,[transport]);eq(v3.lodging_options,[lodging]);
  const v1={...v2,schema_version:1};delete v1.transportation_options;delete v1.lodging_options;
  eq(B.migrateTrip(v1).events,[]);eq(B.migrateTrip(v1).schema_version,3);
  const saved=B.createTrip({events:[event],transportation_options:[transport],lodging_options:[lodging]});
  eq(B.migrateTrip(saved).events,[event]);ok(B.validateTrip(saved).valid);
  throws(()=>B.migrateTrip({...saved,events:{}}),/array/);throws(()=>B.migrateTrip({...saved,events:bads}),/Event/);throws(()=>B.migrateTrip({...saved,schema_version:4}),/Unsupported/);
  ok(!B.validateTrip({...saved,events:[{}]}).valid);
  eq(E.matchTripEvents(trip).map(x=>x.event.id),E.matchTripEvents({...trip,events:[{...event,affiliate_commission:999999}]}).map(x=>x.event.id));
  const failed=await E.isolateSource('fixture',()=>{throw Error('private details')});eq(failed.status,'UNAVAILABLE');eq(failed.events,[]);eq(failed.error,'EVENT SOURCE UNAVAILABLE');
  eq((await E.isolateSource('bad',async()=>[{}])).status,'UNAVAILABLE');eq((await E.isolateSource('ok',async()=>[event])).events,[event]);
  eq(saved.events,[event]);eq(saved.transportation_options,[transport]);eq(saved.lodging_options,[lodging]);
  return assertions;
};
