'use strict';
const assert=require('assert');
const R=require('../revenue-intelligence');
const B=require('../trip-intelligence');
const registry=require('../data/monetization-opportunity-registry.json');
module.exports=async function(){
 let count=0;const eq=(a,b,m)=>{assert.deepStrictEqual(a,b,m);count++;},ok=(v,m)=>{assert.ok(v,m);count++;},throws=(f,m)=>{assert.throws(f,m);count++;};
 const storage=()=>{const map=new Map();return{getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)}};
 const now='2026-10-06T12:00:00Z';
 const trip=B.createTrip({destination:'Orlando',dates:{start:'2026-10-31',end:'2026-11-02'},budget:{total:1200,reserve:100,currency:'USD'},traveler_count:4,identity:{purpose:'Family vacation'},preferences:{transport:'Fly',lodging:'Hotel',interests:['Events']}});
 eq(B.SCHEMA_VERSION,3);ok(B.validateTrip(B.createTrip()).valid);
 ok(R.validateRegistry(registry).valid);eq(registry.opportunities.length,10);ok(registry.opportunities.every(r=>r.verified_direct_url_available===false));
 ok(!R.validateRegistry({...registry,opportunities:[]}).valid);
 ok(!R.validateRegistry({...registry,opportunities:[...registry.opportunities,registry.opportunities[0]]}).valid);
 ok(!R.validateRegistry({...registry,opportunities:registry.opportunities.map(r=>({...r,affiliate_url:'https://example.com/fake'}))}).valid);
 ok(!R.validateRegistry({...registry,opportunities:registry.opportunities.map(r=>({...r,verified_direct_url_available:true}))}).valid);
 const d=R.contextDimensions(trip,Date.parse(now));eq(d.budget_band,'500_1999');eq(d.group_size_band,'3_5');eq(d.date_horizon,'8_30_DAYS');eq(d.trip_purpose,'FAMILY');eq(d.transport_interest,'FLIGHT');eq(d.lodging_interest,'HOTEL');eq(d.event_interest,'YES');
 ok(!('destination' in d));ok(!('names' in d));
 eq(R.contextDimensions({...trip,budget:{total:0}},Date.parse(now)).budget_band,'UNSET');eq(R.contextDimensions({...trip,dates:{start:'bad'}},Date.parse(now)).date_horizon,'UNKNOWN');
 eq(R.pagePath('/money-os-road-trip-planner/flight-cost-planner/?email=x'),'\/flight-cost-planner/');eq(R.pagePath('/private/address'),'\/');
 eq(R.classifyIntent('PAGE_VIEWED').level,'BROWSING');eq(R.classifyIntent('CALCULATOR_USED').level,'PLANNING');eq(R.classifyIntent('TRANSPORT_COMPARISON_VIEWED').level,'COMPARING');
 eq(R.classifyIntent('BLUEPRINT_GENERATED',{destination_known:true,dates_known:true,budget_known:true}).level,'HIGH_INTENT');eq(R.classifyIntent('BLUEPRINT_GENERATED',{destination_known:true}).level,'PLANNING');
 eq(R.classifyIntent('CATEGORY_SELECTED').level,'PLANNING');eq(R.classifyIntent('PROVIDER_ACTION_CLICKED',{},true).level,'MONETIZABLE_INTENT');
 eq(R.selectTripCategories(trip),['FLIGHTS','ACCOMMODATION','ACTIVITIES']);eq(R.selectTripCategories(B.createTrip()),[]);
 eq(R.selectTripCategories({...trip,preferences:{transport:'Drive',lodging:'No lodging',interests:[]}}),[]);
 eq(R.selectTripCategories(B.createTrip(),['ESIM','TRANSFERS','TRAVEL_INSURANCE','FLIGHT_COMPENSATION']),['TRANSFERS','ESIM','TRAVEL_INSURANCE','FLIGHT_COMPENSATION']);
 eq(R.selectTripCategories({...trip,affiliate_commission:99999}),R.selectTripCategories(trip));
 const actionInput={category:'FLIGHTS',url:'https://example.com/verified-fixture',provider:'FIXTURE_PROVIDER',relationship_status:'APPROVED',verified_at:now};
 throws(()=>R.createProviderAction(actionInput),/runtime/);throws(()=>R.createProviderAction({...actionInput,url:'http://example.com'},{trusted:true}),/HTTPS/);throws(()=>R.createProviderAction({...actionInput,url:'https://user:password@example.com'},{trusted:true}),/HTTPS/);throws(()=>R.createProviderAction({...actionInput,relationship_status:'UNKNOWN'},{trusted:true}),/approved/);
 const action=R.createProviderAction(actionInput,{trusted:true});eq(R.actionUrl(action),actionInput.url);eq(R.actionUrl(JSON.parse(JSON.stringify(action))),null);ok(Object.isFrozen(action));
 const visitor=R.makeDemandEvent('PAGE_VIEWED',{source_page:'/'},{},null,now);eq(visitor.state,'VISITOR');eq(visitor.acquisition,'UNKNOWN');
 const click=R.makeDemandEvent('PROVIDER_ACTION_CLICKED',{category:'FLIGHTS',source_page:'/flight-cost-planner/'},{},action,now);eq(click.state,'PROVIDER_CLICK');eq(click.intent_level,'MONETIZABLE_INTENT');
 const available=R.makeDemandEvent('PROVIDER_ACTION_SHOWN',{category:'FLIGHTS'},{},action,now);eq(available.state,'MONETIZABLE_ACTION_AVAILABLE');
 const qualified=R.makeDemandEvent('BLUEPRINT_GENERATED',d,{destination_known:true,dates_known:true,budget_known:true},null,now);eq(qualified.state,'QUALIFIED_INTENT');
 throws(()=>R.makeDemandEvent('PROVIDER_ACTION_CLICKED',{category:'FLIGHTS'}),/runtime/);throws(()=>R.makeDemandEvent('PROVIDER_ACTION_CLICKED',{category:'ESIM'},{},action,now),/matching/);
 throws(()=>R.makeDemandEvent('ATTRIBUTED_BOOKING'),/Invalid/);throws(()=>R.makeDemandEvent('CLEARED_REVENUE'),/Invalid/);
 for(const key of ['name','email','phone','exact_address','payment_data','health','government_id','latitude','longitude','destination','location_history']){throws(()=>R.makeDemandEvent('PAGE_VIEWED',{[key]:'private'}),/privacy/);ok(!R.validateDemandEvent({...visitor,[key]:'private'}));}
 ok(!R.validateDemandEvent({...visitor,state:'CLEARED_REVENUE'}));ok(!R.validateDemandEvent({...visitor,state:'PROVIDER_CLICK'}));ok(!R.validateDemandEvent({...visitor,reasons:['private email john@example.com']}));
 const local=R.demandStore(storage());local.append(visitor);local.append(qualified);local.append(click);eq(local.read().length,3);eq(JSON.parse(local.export()).events.length,3);local.clear();eq(local.read(),[]);
 for(let i=0;i<1003;i++)local.append(visitor);eq(local.read().length,1000);local.clear();
 const badStorage=storage();badStorage.setItem(R.DEMAND_KEY,'{broken');throws(()=>R.demandStore(badStorage).read(),/JSON/);R.demandStore(badStorage).clear();eq(R.demandStore(badStorage).read(),[]);
 const report={id:'fixture-commission-1',provider:'FIXTURE_PROVIDER',category:'FLIGHTS',external_reference:'fixture-reference-1',booking_date:'2026-09-01',commission_currency:'USD',commission_amount:12,state:'COMMISSION_PENDING',reported_at:now,cleared_at:null,evidence_source:'REDACTED_PROVIDER_REPORT',record_origin:'USER_IMPORTED'};
 ok(R.validateReport(report).valid);eq(R.importReports({version:1,records:[report]})[0].record_origin,'USER_IMPORTED');
 const approved={...report,state:'PROVIDER_APPROVED'};const cleared={...report,state:'CLEARED_REVENUE',cleared_at:'2026-10-05T10:00:00Z'};
 eq(R.moneySummary([report]).verifiedClearedByCurrency,{});eq(R.moneySummary([approved]).verifiedClearedByCurrency,{});eq(R.moneySummary([cleared]).verifiedClearedByCurrency,{});eq(R.moneySummary([cleared]).importedClearedByCurrency,{USD:12});
 const milestones=(events=[],reports=[])=>Object.fromEntries(R.milestones(events,reports).map(m=>[m.name,m.achieved]));
 eq(milestones([click])['FIRST ATTRIBUTED BOOKING'],false);eq(milestones([click])['FIRST CLEARED DOLLAR'],false);eq(milestones([qualified])['FIRST QUALIFIED INTENT'],true);eq(milestones([click])['FIRST ELIGIBLE PROVIDER CLICK'],true);eq(milestones([visitor])['FIRST ORGANIC VISITOR'],false);
 eq(milestones([], [approved])['FIRST APPROVED COMMISSION'],false,'Imported claim cannot become proof');eq(milestones([], [cleared])['FIRST CLEARED DOLLAR'],false);
 throws(()=>R.verifyProviderReport(cleared,{trusted:true}),/payout/);throws(()=>R.verifyProviderReport(report),/verified/);
 const verified=R.verifyProviderReport(cleared,{trusted:true,evidenceKind:'PAYOUT_RECEIPT'});eq(R.moneySummary([verified]).verifiedClearedByCurrency,{USD:12});eq(milestones([], [verified])['FIRST CLEARED DOLLAR'],true);eq(milestones([], [verified])['FIRST $10 CLEARED'],true);eq(milestones([], [verified])['FIRST $100 CLEARED'],false);
 eq(milestones([], [JSON.parse(JSON.stringify(verified))])['FIRST CLEARED DOLLAR'],false,'Persisted money proof loses runtime trust');
 const hundred=R.verifyProviderReport({...cleared,id:'fixture-100',external_reference:'fixture-100',commission_amount:100},{trusted:true,evidenceKind:'PAYOUT_RECEIPT'});eq(milestones([], [hundred])['FIRST $100 CLEARED'],true);
 const euro=R.verifyProviderReport({...cleared,commission_currency:'EUR',commission_amount:200},{trusted:true,evidenceKind:'PAYOUT_RECEIPT'});eq(milestones([], [euro])['FIRST $100 CLEARED'],false,'No invented FX');
 const pendingVerified=R.verifyProviderReport(report,{trusted:true});eq(milestones([], [pendingVerified])['FIRST ATTRIBUTED BOOKING'],true);eq(milestones([], [pendingVerified])['FIRST CLEARED DOLLAR'],false);
 const reversed=R.verifyProviderReport({...report,state:'REVERSED',reported_at:'2026-10-06T13:00:00Z'},{trusted:true});eq(R.moneySummary([verified,reversed]).verifiedClearedByCurrency,{});eq(milestones([], [verified,reversed])['FIRST CLEARED DOLLAR'],false);
 const canceled=R.verifyProviderReport({...report,state:'CANCELED',reported_at:'2026-10-06T13:00:00Z'},{trusted:true});eq(milestones([], [verified,canceled])['FIRST CLEARED DOLLAR'],false);
 const rows=Array.from({length:7},(_,i)=>R.verifyProviderReport({...cleared,id:'daily-'+i,external_reference:'daily-'+i,cleared_at:`2026-09-${String(i+1).padStart(2,'0')}T10:00:00Z`,commission_amount:1},{trusted:true,evidenceKind:'PAYOUT_RECEIPT'}));eq(milestones([],rows)['FIRST RECURRING DAILY REVENUE'],true);eq(milestones([],rows.slice(0,6))['FIRST RECURRING DAILY REVENUE'],false);
 const weekly=[1,8,15,22].map((day,i)=>R.verifyProviderReport({...cleared,id:'weekly-'+i,external_reference:'weekly-'+i,cleared_at:`2026-09-${String(day).padStart(2,'0')}T10:00:00Z`,commission_amount:1},{trusted:true,evidenceKind:'PAYOUT_RECEIPT'}));eq(milestones([],weekly)['FIRST RECURRING WEEKLY REVENUE'],true);eq(milestones([],weekly.slice(0,3))['FIRST RECURRING WEEKLY REVENUE'],false);
 const cents=Array.from({length:10},(_,i)=>R.verifyProviderReport({...cleared,id:'cents-'+i,external_reference:'cents-'+i,commission_amount:0.1},{trusted:true,evidenceKind:'PAYOUT_RECEIPT'}));eq(milestones([],cents)['FIRST CLEARED DOLLAR'],true);
 const invalid=[{...cleared,commission_amount:0.001},{...report,commission_amount:1e100},{...report,email:'private@example.com'},{...report,commission_amount:-1},{...report,commission_amount:'12'},{...report,commission_amount:true},{...report,state:'CLICK'},{...report,booking_date:'2026-02-30'},{...report,cleared_at:now},{...cleared,cleared_at:null},{...cleared,reported_at:'2026-10-01T00:00:00Z'},{...report,reported_at:'invalid'}];
 invalid.forEach(r=>{ok(!R.validateReport(r).valid);throws(()=>R.importReports({version:1,records:[r]}),/Invalid|privacy|requires|Only|date|whole cents|precision/)});
 throws(()=>R.importReports({version:1,records:[report,report]}),/Duplicate/);throws(()=>R.importReports({version:2,records:[]}),/version/);throws(()=>R.importReports({version:1,records:{}}),/array/);
 const rs=R.reportStore(storage());rs.replace({version:1,records:[cleared]});eq(rs.read()[0].record_origin,'USER_IMPORTED');throws(()=>rs.replace({version:1,records:invalid}),/privacy|whole cents/);eq(rs.read().length,1,'Malformed import is atomic');eq(JSON.parse(rs.export()).records.length,1);rs.clear();eq(rs.read(),[]);
 const insight=R.demandInsights([visitor,qualified,click]);eq(insight.attention.PAGE_VIEWED,1);eq(insight.intent.PROVIDER_ACTION_CLICKED,1);eq(insight.categories.FLIGHTS.providerClicks,1);ok(!('money' in insight));eq(insight.label,'LOCAL BROWSER SIGNALS');ok(insight.observations.some(s=>s.includes('FLIGHTS')&&s.includes('local')));eq(insight.categories.FLIGHTS.highIntentActions,1);
 return count;
};
