"use strict";
const assert=require("assert"),B=require("../trip-intelligence.js"),S=require("../source-intelligence.js");
let assertions=0;const ok=(v,m)=>{assert(v,m);assertions++},eq=(a,b,m)=>{assert.deepEqual(a,b,m);assertions++};
let t=B.createTrip();eq(t.schema_version,1);ok(B.validateTrip(t).valid);ok(B.validateTrip(JSON.parse(JSON.stringify(t))).valid,"canonical serialization");
t.budget={total:1000,reserve:200,currency:"USD"};t.traveler_count=4;t.travelers=[1,2,3,4].map((x,i)=>({label:`T${x}`,amount_committed:250,amount_paid:i<3?250:0,commitment_state:i<3?"FULL_SHARE_FUNDED":"ACCEPTED"}));
let m=B.budgetMetrics(t);eq([m.spendable,m.plannedShare,m.fundedAmount,m.unfundedGap,m.plannedCount,m.committed,m.funded],[800,250,750,250,4,4,3]);
let d=B.dropoutScenario(t,1);eq(d.remaining,3);ok(Math.abs(d.newShare-333.3333333333333)<.001);ok(Math.abs(d.increasePerRemaining-83.33333333333331)<.001);eq(d.totalFundingShortage,500);
let u=B.dropoutScenario(t,0,true,true);eq(u.dropouts,1);eq(u.totalFundingShortage,250);eq(u.remaining,3);
let noRows=B.createTrip({budget:{total:1200,reserve:120,currency:"USD"},traveler_count:4});let noRowsDrop=B.dropoutScenario(noRows,1);eq(noRowsDrop.remaining,3);eq(noRowsDrop.newShare,400);
let c=B.cancellationExposure([{booking_price:500,deposit_paid:200,amount_paid_beyond_deposit:100,remaining_balance:200,refundable_amount:150,nonrefundable_amount:150,change_rebooking_fee:25,provider_cancellation_fee:10,provider_no_show_fee:0,credit_voucher_possibility:"UNKNOWN",policy_status:"USER-ENTERED"}]);eq([c.totalBookedValue,c.totalAlreadyPaid,c.remainingBalance,c.estimatedRecoverable,c.estimatedNonrefundable,c.estimatedFees,c.netEstimatedLoss],[500,300,200,150,150,35,185]);
let c2=B.cancellationExposure([{booking_price:500,deposit_paid:100,amount_paid_beyond_deposit:0,refundable_amount:0,nonrefundable_amount:200,change_rebooking_fee:0,provider_cancellation_fee:0,provider_no_show_fee:0,policy_status:"VERIFIED"}]);eq(c2.netEstimatedLoss,200);
let f=B.hiddenFeeMetrics([{status:"UNKNOWN",amount:null},{status:"USER-ENTERED",amount:25},{status:"NOT APPLICABLE",amount:99}]);eq(f,{total:25,counted:1,unknown:1});
ok(!B.validateTrip({...t,schema_version:99}).valid);ok(!B.validateTrip(null).valid);ok(!B.validateTrip({...t,budget:{total:1,reserve:2}}).valid);
let badFee=JSON.parse(JSON.stringify(t));badFee.hidden_fees=[{category:"made-up fee",status:"UNKNOWN",amount:null}];ok(!B.validateTrip(badFee).valid);
let badDates=JSON.parse(JSON.stringify(t));badDates.dates={start:"2026-12-10",end:"2026-12-01",flexibility:"fixed"};ok(!B.validateTrip(badDates).valid);
eq(B.budgetMetrics(B.createTrip()).plannedShare,0);eq(B.dropoutScenario(B.createTrip(),2).remaining,0);
let partial=B.createTrip({budget:{total:1000,reserve:100,currency:"USD"},traveler_count:4,travelers:[{amount_committed:250,amount_paid:250,commitment_state:"FULL_SHARE_FUNDED"},{amount_committed:250,amount_paid:250,commitment_state:"FULL_SHARE_FUNDED"}]});let group=B.resilience(partial).find(x=>x.label==="Group commitment");eq(group.status,"WATCH");ok(group.reason.includes("2 planned traveler(s) have no record yet"));
let fresh=S.classifyFreshness({fact_type:"LIVE",retrieved_at:"2026-01-01T00:00:00Z",freshness_seconds:3600},Date.parse("2026-01-01T00:30:00Z"));eq([fresh.label,fresh.status],["LIVE","fresh"]);eq(S.classifyFreshness({fact_type:"LIVE",retrieved_at:"2026-01-01T00:00:00Z",freshness_seconds:3600},Date.parse("2026-01-01T03:00:00Z")).status,"stale");eq(S.classifyFreshness({}).label,"UNKNOWN");
let weekly=S.classifyFreshness({fact_type:"WEEKLY_GOVERNMENT_DATA",retrieved_at:"2026-01-01T00:00:00Z"},Date.parse("2026-01-11T00:00:00Z"));eq(weekly.status,"aging");
eq(S.matchAlias("Los Angeles, CA","ca"),true);eq(S.matchAlias("Cancun, Mexico","ca"),false);
const places=[{label:"California",aliases:["california","ca"]},{label:"U.S. average",aliases:["united states","us","u.s."]}];eq(S.pickFuelPlace(places,"Cancun, Mexico").label,"U.S. average");
console.log(`Suitcase Brain: ${assertions} assertions passed`);
