(function () {
  "use strict";
  const B = window.SuitcaseBrain, T = window.TransportLodgingIntelligence, form = document.getElementById("trip-intake"); if (!B || !T || !form) return;
  const $ = id => document.getElementById(id), money = n => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(Number(n) || 0);
  let trip = B.createTrip(), step = 0;
  const steps = [...document.querySelectorAll(".planner-step")];
  const escape = value => String(value ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const value = id => $(id)?.value.trim() || "", number = id => Number($(id)?.value || 0), checked = id => !!$(id)?.checked;
  const optionalNumber = id => value(id) === "" ? null : Number(value(id));
  function showStep(index) { step = Math.max(0, Math.min(steps.length - 1, index)); steps.forEach((el, i) => { el.hidden = i !== step; }); $("stepLabel").textContent = `Step ${step + 1} of ${steps.length}`; $("prevStep").hidden = step === 0; $("nextStep").hidden = step === steps.length - 1; steps[step].querySelector("input, select, textarea, button")?.focus(); }
  function collect() {
    trip.updated_at = new Date().toISOString(); trip.identity = { title: value("tripTitle"), purpose: value("purpose"), vibe: value("vibe") };
    trip.origin = value("origin"); trip.destination = value("destination"); trip.destination_unknown = checked("flexDestination");
    trip.dates = { start: value("startDate"), end: value("endDate"), flexibility: value("dateFlexibility") };
    trip.budget = { total: number("budget"), reserve: number("reserve"), currency: value("currency") || "USD" };
    trip.traveler_count = Math.max(1, number("travelerCount"));
    trip.preferences = { lodging: value("lodging"), transport: value("transport"), walking: value("walking"), driving: value("driving"), interests: [...document.querySelectorAll('[name="interest"]:checked')].map(x => x.value), culture_community: value("culture"), food: value("food"), nightlife: value("nightlife"), outdoor_adventure: value("outdoor") };
    trip.needs = { pet_service_animal: value("petNeeds"), accessibility: value("accessibilityNeeds") };
    trip.modes = { business: checked("businessMode"), group: checked("groupMode"), safe_night_no_driving: checked("safeNightMode"), vendor_business_opportunity: checked("vendorMode") };
    trip.emergency = { scenario: value("emergencyScenario"), personal_safety: checked("personalSafety"), contacts: value("emergencyContacts"), documents_notes: value("documentsNotes"), booking_owners: value("bookingOwners") };
    return trip;
  }
  function travelerRow(t = {}) { return `<div class="editor-row traveler-row"><label>Label (optional)<input data-field="label" value="${escape(t.label)}"></label><label>Age / band<input data-field="age_band" value="${escape(t.age_band)}" placeholder="Adult, 14, senior"></label><label>Payment responsibility<input data-field="payment_responsibility" value="${escape(t.payment_responsibility)}" placeholder="Self / organizer"></label><label>Committed<input data-field="amount_committed" type="number" min="0" step=".01" value="${Number(t.amount_committed)||0}"></label><label>Paid<input data-field="amount_paid" type="number" min="0" step=".01" value="${Number(t.amount_paid)||0}"></label><label>Commitment state<select data-field="commitment_state">${B.COMMITMENT_STATES.map(s=>`<option ${s===(t.commitment_state||"INVITED")?"selected":""}>${s}</option>`).join("")}</select></label><button class="secondary remove-row" type="button">Remove</button></div>`; }
  function reservationRow(r = {}) { const fields=[["provider","Provider"],["description","Description"],["booking_price","Booking price","number"],["deposit_paid","Deposit paid","number"],["amount_paid_beyond_deposit","Other amount paid","number"],["remaining_balance","Remaining balance","number"],["paid_by","Paid by traveler/group"],["booking_date","Booking date","date"],["cancellation_deadline","Cancellation deadline","date"],["refundable_amount","Refundable amount","number"],["nonrefundable_amount","Nonrefundable amount","number"],["change_rebooking_fee","Change/rebooking fee","number"],["provider_cancellation_fee","Cancellation fee","number"],["provider_no_show_fee","No-show fee","number"],["credit_voucher_possibility","Credit/voucher possibility"],["confirmation_reference","Confirmation/reference"],["source","Policy source URL","url"],["notes","Notes"]]; return `<div class="editor-row reservation-row"><label>Category<select data-field="category">${B.RESERVATION_CATEGORIES.map(x=>`<option ${x===(r.category||"other")?"selected":""}>${x}</option>`).join("")}</select></label>${fields.map(([key,label,type="text"])=>`<label>${label}<input data-field="${key}" type="${type}" ${type==="number"?'min="0" step=".01"':''} value="${escape(r[key])}"></label>`).join("")}<label>Policy status<select data-field="policy_status"><option>UNKNOWN</option><option ${r.policy_status==="USER-ENTERED"?"selected":""}>USER-ENTERED</option><option ${r.policy_status==="VERIFIED"?"selected":""}>VERIFIED</option></select></label><button class="secondary remove-row" type="button">Remove</button></div>`; }
  function feeRows() { $("feeRows").innerHTML = trip.hidden_fees.map((f,i)=>`<div class="fee-row" data-index="${i}"><strong>${escape(f.category)}</strong><label>Status<select data-field="status">${B.FEE_STATUSES.map(s=>`<option ${s===f.status?"selected":""}>${s}</option>`).join("")}</select></label><label>Amount (blank if unknown)<input data-field="amount" type="number" min="0" step=".01" value="${f.amount==null?"":f.amount}"></label><label>Source / note<input data-field="source" value="${escape(f.source)}"></label></div>`).join(""); }
  function syncRows() { trip.travelers = [...document.querySelectorAll(".traveler-row")].map(row => Object.fromEntries([...row.querySelectorAll("[data-field]")].map(el=>[el.dataset.field, el.type==="number"?Number(el.value||0):el.value]))); trip.traveler_count = Math.max(trip.traveler_count, trip.travelers.length || 1); trip.reservations = [...document.querySelectorAll(".reservation-row")].map(row => Object.fromEntries([...row.querySelectorAll("[data-field]")].map(el=>[el.dataset.field, el.type==="number"?Number(el.value||0):el.value]))); [...document.querySelectorAll(".fee-row")].forEach(row=>{ const f=trip.hidden_fees[Number(row.dataset.index)]; row.querySelectorAll("[data-field]").forEach(el=>f[el.dataset.field]=el.dataset.field==="amount"?(el.value===""?null:Number(el.value)):el.value); }); }
  function renderBlueprint() { collect(); syncRows(); const valid=B.validateTrip(trip); if(!valid.valid){$("planError").textContent=valid.errors.join(" "); return;} $("planError").textContent=""; const b=B.budgetMetrics(trip), c=B.cancellationExposure(trip.reservations), fees=B.hiddenFeeMetrics(trip.hidden_fees); const one=B.dropoutScenario(trip,1), two=B.dropoutScenario(trip,2), unpaid=B.dropoutScenario(trip,0,true,true); const special=Object.entries(trip.modes).filter(([,on])=>on).map(([name])=>name.replaceAll("_"," ")).join(", ")||"None selected";
    $("blueprintSummary").innerHTML=[["TRIP TYPE",trip.identity.purpose||"Not set"],["GROUP",`${trip.traveler_count} planned · ${b.committed} committed · ${b.funded} funded`],["DATES",trip.dates.start?`${trip.dates.start} → ${trip.dates.end||"open"} (${trip.dates.flexibility})`:"Not set"],["DESTINATION",trip.destination_unknown?"Find me somewhere":trip.destination||"Not set"],["BUDGET",money(b.total)],["RESERVE",money(b.reserve)],["FUNDED AMOUNT",money(b.fundedAmount)],["FUNDING GAP",money(b.unfundedGap)],["PER-PERSON SHARE",money(b.plannedShare)],["DROPOUT EXPOSURE",money(one.totalFundingShortage)],["TRANSPORTATION",trip.preferences.transport],["LODGING",trip.preferences.lodging],["INTERESTS",trip.preferences.interests.join(", ")||"None selected"],["SPECIAL MODES",special]].map(([a,v])=>`<div><span>${escape(a)}</span><strong>${escape(v)}</strong></div>`).join("");
    $("dropoutResults").innerHTML=[["1 person drops",one],["2 people drop",two],["One unpaid traveler never pays",unpaid]].map(([label,x])=>`<tr><th>${label}</th><td>${money(x.currentShare)}</td><td>${x.remaining?money(x.newShare):"No travelers remain"}</td><td>${money(x.increasePerRemaining)}</td><td>${money(x.totalFundingShortage)}</td></tr>`).join("");
    $("cancelResults").innerHTML=[["Total booked value",c.totalBookedValue],["Total already paid",c.totalAlreadyPaid],["Estimated recoverable",c.estimatedRecoverable],["Estimated nonrefundable exposure",c.estimatedNonrefundable],["Estimated change/cancellation fees",c.estimatedFees],["Net estimated loss",c.netEstimatedLoss]].map(([k,v])=>`<div><span>${k}</span><strong>${money(v)}</strong></div>`).join("")+`<div><span>Credits / vouchers</span><strong>${escape(c.creditsVouchers.join(", ")||"UNKNOWN")}</strong></div><p class="source-note">${c.unknownPolicies} reservation policy record(s) are UNKNOWN. No provider rule was invented.</p>`;
    $("feeSummary").textContent=`${money(fees.total)} in entered/known/verified fees · ${fees.unknown} unknown item(s). Unknown fees are not silently priced.`;
    $("resilienceCards").innerHTML=B.resilience(trip).map(x=>`<article class="status-card status-${x.status.toLowerCase()}"><span>${x.status}</span><h4>${escape(x.label)}</h4><p>${escape(x.reason)}</p></article>`).join(""); renderIntelligence();
    $("planResults").hidden=false; window.dispatchEvent(new CustomEvent("suitcasebrain:blueprint",{detail:trip})); $("planResults").scrollIntoView({behavior:matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth"});
  }
  function populate(t) { trip=t; const set=(id,v)=>{if($(id))$(id).value=v??""},check=(id,v)=>{if($(id))$(id).checked=!!v}; set("tripTitle",t.identity.title);set("purpose",t.identity.purpose);set("vibe",t.identity.vibe);set("origin",t.origin);set("destination",t.destination);check("flexDestination",t.destination_unknown);set("startDate",t.dates.start);set("endDate",t.dates.end);set("dateFlexibility",t.dates.flexibility);set("budget",t.budget.total);set("reserve",t.budget.reserve);set("currency",t.budget.currency);set("travelerCount",t.traveler_count);["lodging","transport","walking","driving"].forEach(k=>set(k,t.preferences[k]));set("culture",t.preferences.culture_community);set("food",t.preferences.food);set("nightlife",t.preferences.nightlife);set("outdoor",t.preferences.outdoor_adventure);set("petNeeds",t.needs.pet_service_animal);set("accessibilityNeeds",t.needs.accessibility);Object.keys(t.modes).forEach(k=>check({business:"businessMode",group:"groupMode",safe_night_no_driving:"safeNightMode",vendor_business_opportunity:"vendorMode"}[k],t.modes[k]));document.querySelectorAll('[name="interest"]').forEach(el=>el.checked=t.preferences.interests.includes(el.value));set("emergencyScenario",t.emergency.scenario);check("personalSafety",t.emergency.personal_safety);set("emergencyContacts",t.emergency.contacts);set("documentsNotes",t.emergency.documents_notes);set("bookingOwners",t.emergency.booking_owners);$("travelerRows").innerHTML=t.travelers.map(travelerRow).join("");$("reservationRows").innerHTML=t.reservations.map(reservationRow).join("");feeRows();renderIntelligence();showStep(0); }

  function optionCard(option, kind) { const p=T.priceCompleteness(option,kind), cancel=T.cancellationExposure(option), title=kind==="transport"?`${option.mode.replaceAll("_"," ")} · ${option.provider}`:`${option.property} · ${option.category.replaceAll("_"," ")}`, unit=kind==="transport"&&option.traveler_count?`${money(p.knownTotal/option.traveler_count)} / traveler`:kind==="lodging"&&option.nights?`${money(p.knownTotal/option.nights)} / night`:"UNKNOWN"; return `<article class="option-card" data-option-id="${escape(option.id)}"><div class="option-head"><span class="intel-badge">${escape(option.record_origin)}</span><h4>${escape(title)}</h4></div><strong class="intel-value">${money(p.knownTotal)} known</strong><p>${escape(unit)} · ${escape(p.label)}</p><p class="muted">Known-cost coverage: ${escape(p.coverageLabel)}. Deposit/hold: ${p.depositHold==null?"UNKNOWN":money(p.depositHold)}. ${escape(cancel.label)}.</p><p class="muted">Source: ${escape(option.source.source_name)} · ${escape(option.source.fact_type)} · Availability: ${escape(option.availability_status)}</p><div class="button-row"><button class="secondary edit-option" data-kind="${kind}" data-id="${escape(option.id)}" type="button">Edit</button><button class="secondary remove-option" data-kind="${kind}" data-id="${escape(option.id)}" type="button">Remove</button></div></article>`; }
  function comparisonCards(results, options) { return results.map(x=>{const winner=options.find(o=>o.id===x.winner_id);return `<article class="comparison-card"><strong>${escape(x.label)}</strong><span>${winner?escape(winner.property||winner.service_name||winner.provider||winner.mode):escape(x.status)}</span><p>${escape(x.basis)}</p></article>`;}).join(""); }
  function renderIntelligence(){trip.transportation_options ||= [];trip.lodging_options ||= [];$("transportOptions").innerHTML=trip.transportation_options.length?trip.transportation_options.map(x=>optionCard(x,"transport")).join(""):'<p class="empty-state">No user-entered transportation quotes yet.</p>';$("lodgingOptions").innerHTML=trip.lodging_options.length?trip.lodging_options.map(x=>optionCard(x,"lodging")).join(""):'<p class="empty-state">No user-entered lodging quotes yet.</p>';$("transportComparison").innerHTML=comparisonCards(T.compareTransport(trip.transportation_options),trip.transportation_options);$("lodgingComparison").innerHTML=comparisonCards(T.compareLodging(trip.lodging_options),trip.lodging_options);}
  function transportFromForm(){let fuel=optionalNumber("quoteTransportFuel"),distance=optionalNumber("quoteTransportDistance"),mpg=optionalNumber("quoteTransportMpg"),fuelPrice=optionalNumber("quoteTransportFuelPrice");if(fuel==null&&distance!=null&&mpg!=null&&fuelPrice!=null)fuel=T.drivingFuelCost({distance_miles:distance,trip_direction:value("quoteTransportDirection"),mpg,fuel_price:fuelPrice}).cost;return T.normalizeTransportOption({id:value("transportEditId")||undefined,mode:value("quoteTransportMode"),provider:value("quoteTransportProvider"),service_name:value("quoteTransportService"),traveler_count:number("quoteTransportTravelers"),duration_minutes:optionalNumber("quoteTransportDuration"),trip_direction:value("quoteTransportDirection"),driving_details:{distance_miles:distance,mpg,fuel_price:fuelPrice,fuel_reference:value("quoteTransportFuelBasis")},base_price:optionalNumber("quoteTransportBase"),mandatory_fees:optionalNumber("quoteTransportFees"),optional_fees:optionalNumber("quoteTransportOptional"),baggage:optionalNumber("quoteTransportBags"),fuel,parking:optionalNumber("quoteTransportRoad"),deposit_hold:optionalNumber("quoteTransportDeposit"),nonrefundable_amount:optionalNumber("quoteTransportNonrefundable"),change_cancel_fee:optionalNumber("quoteTransportCancelFee"),policy_status:value("quoteTransportPolicy"),currency:trip.budget.currency,source:{fact_type:"USER_ENTERED",source_name:"Traveler"}});}
  function lodgingFromForm(){return T.normalizeLodgingOption({id:value("lodgingEditId")||undefined,category:value("quoteLodgingCategory"),provider:value("quoteLodgingProvider"),property:value("quoteLodgingProperty"),nights:number("quoteLodgingNights"),rooms:number("quoteLodgingRooms"),occupancy:number("quoteLodgingOccupancy"),base_stay_price:optionalNumber("quoteLodgingBase"),mandatory_fees:optionalNumber("quoteLodgingFees"),resort_destination_fees:optionalNumber("quoteLodgingExtra"),parking:optionalNumber("quoteLodgingParking"),deposit_hold:optionalNumber("quoteLodgingDeposit"),optional_cost:optionalNumber("quoteLodgingOptional"),nonrefundable_amount:optionalNumber("quoteLodgingNonrefundable"),cancellation_fee:optionalNumber("quoteLodgingCancelFee"),policy_status:value("quoteLodgingPolicy"),currency:trip.budget.currency,amenities:{parking:checked("quoteLodgingParkingIncluded"),breakfast:checked("quoteLodgingBreakfastIncluded")},location_fit:checked("quoteLodgingLocationFit")?"MATCH":"UNKNOWN",source:{fact_type:"USER_ENTERED",source_name:"Traveler"}});}
  function resetQuoteForm(kind){const form=$(kind==="transport"?"transportQuoteForm":"lodgingQuoteForm");form.reset();$(kind==="transport"?"transportEditId":"lodgingEditId").value="";if(kind==="transport")$("quoteTransportTravelers").value=trip.traveler_count||1;}
  function editOption(kind,id){const option=(kind==="transport"?trip.transportation_options:trip.lodging_options).find(x=>x.id===id);if(!option)return;const set=(id,v)=>$(id).value=v??"";if(kind==="transport"){set("transportEditId",id);set("quoteTransportMode",option.mode);set("quoteTransportProvider",option.provider);set("quoteTransportService",option.service_name);set("quoteTransportTravelers",option.traveler_count);set("quoteTransportBase",option.costs.base_price.value);set("quoteTransportFees",option.costs.mandatory_fees.value);set("quoteTransportOptional",option.costs.optional_fees.value);set("quoteTransportBags",option.costs.baggage.value);set("quoteTransportFuel",option.costs.fuel.value);set("quoteTransportDistance",option.driving_details?.distance_miles);set("quoteTransportMpg",option.driving_details?.mpg);set("quoteTransportFuelPrice",option.driving_details?.fuel_price);set("quoteTransportFuelBasis",option.driving_details?.fuel_reference);set("quoteTransportDirection",option.trip_direction);set("quoteTransportRoad",option.costs.parking.value);set("quoteTransportDeposit",option.costs.deposit_hold.value);set("quoteTransportDuration",option.duration_minutes);set("quoteTransportNonrefundable",option.nonrefundable_amount);set("quoteTransportCancelFee",option.change_cancel_fee);set("quoteTransportPolicy",option.policy_status);$("transportQuoteForm").closest("details").open=true;$("quoteTransportProvider").focus();}else{set("lodgingEditId",id);set("quoteLodgingCategory",option.category);set("quoteLodgingProvider",option.provider);set("quoteLodgingProperty",option.property);set("quoteLodgingNights",option.nights);set("quoteLodgingRooms",option.rooms);set("quoteLodgingOccupancy",option.occupancy);set("quoteLodgingBase",option.costs.base_stay_price.value);set("quoteLodgingFees",option.costs.mandatory_fees.value);set("quoteLodgingExtra",option.costs.resort_destination_fees.value);set("quoteLodgingParking",option.costs.parking.value);set("quoteLodgingDeposit",option.costs.deposit_hold.value);set("quoteLodgingOptional",option.costs.optional_cost.value);set("quoteLodgingNonrefundable",option.nonrefundable_amount);set("quoteLodgingCancelFee",option.cancellation_fee);set("quoteLodgingPolicy",option.policy_status);$("quoteLodgingParkingIncluded").checked=option.amenities.parking===true;$("quoteLodgingBreakfastIncluded").checked=option.amenities.breakfast===true;$("quoteLodgingLocationFit").checked=option.location_fit==="MATCH";$("lodgingQuoteForm").closest("details").open=true;$("quoteLodgingProperty").focus();}}
  $("nextStep").onclick=()=>showStep(step+1); $("prevStep").onclick=()=>showStep(step-1); form.onsubmit=e=>{e.preventDefault();renderBlueprint();};
  $("addTraveler").onclick=()=>$("travelerRows").insertAdjacentHTML("beforeend",travelerRow()); $("addReservation").onclick=()=>$("reservationRows").insertAdjacentHTML("beforeend",reservationRow());
  document.addEventListener("click",e=>{if(e.target.matches(".remove-row"))e.target.closest(".editor-row").remove();if(e.target.matches(".remove-option")){const key=e.target.dataset.kind==="transport"?"transportation_options":"lodging_options";trip[key]=trip[key].filter(x=>x.id!==e.target.dataset.id);renderIntelligence();}if(e.target.matches(".edit-option"))editOption(e.target.dataset.kind,e.target.dataset.id);});
  $("saveTrip").onclick=()=>{collect();syncRows();const v=B.validateTrip(trip);if(!v.valid)return alert(v.errors.join("\n"));localStorage.setItem(B.STORAGE_KEY,JSON.stringify(trip));$("persistenceStatus").textContent="Trip saved in this browser.";};
  $("loadTrip").onclick=()=>{try{const raw=localStorage.getItem(B.STORAGE_KEY)||localStorage.getItem(B.LEGACY_STORAGE_KEY);if(!raw)throw Error("No saved trip found in this browser.");const original=JSON.parse(raw),t=B.migrateTrip(original),v=B.validateTrip(t);if(!v.valid)throw Error(v.errors.join(" "));populate(t);$("persistenceStatus").textContent=original.schema_version===1?"Saved V1 trip migrated to V2 in memory. Save to retain the migration.":"Saved trip loaded.";}catch(e){$("persistenceStatus").textContent=e.message;}};
  $("startOver").onclick=()=>{if(!confirm("Start over? The saved copy remains until you save again."))return;populate(B.createTrip());$("planResults").hidden=true;$("persistenceStatus").textContent="Started a new local trip.";};
  $("exportTrip").onclick=()=>{collect();syncRows();const blob=new Blob([JSON.stringify(trip,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="suitcase-brain-trip.json";a.click();URL.revokeObjectURL(a.href);};
  $("importTrip").onchange=async e=>{try{const original=JSON.parse(await e.target.files[0].text()),t=B.migrateTrip(original),v=B.validateTrip(t);if(!v.valid)throw Error(v.errors.join(" "));populate(t);$("persistenceStatus").textContent=`Validated trip imported${original.schema_version===1?" and migrated from V1":""}. Save it to retain it in this browser.`;}catch(err){$("persistenceStatus").textContent=`Import rejected: ${err.message}`;}e.target.value="";};
  $("emergencyToggle").onclick=()=>{$("emergencyPanel").hidden=!$("emergencyPanel").hidden;if(!$("emergencyPanel").hidden)$("emergencyScenario").focus();};
  $("quoteTransportMode").innerHTML=T.TRANSPORT_MODES.map(x=>`<option>${x}</option>`).join("");$("quoteLodgingCategory").innerHTML=T.LODGING_CATEGORIES.map(x=>`<option>${x}</option>`).join("");
  $("transportQuoteForm").onsubmit=e=>{e.preventDefault();const option=transportFromForm(),v=T.validateTransportOption(option);if(!v.valid){$("transportFormError").textContent=v.errors.join(" ");return;}const index=trip.transportation_options.findIndex(x=>x.id===option.id);if(index<0)trip.transportation_options.push(option);else trip.transportation_options[index]=option;$("transportFormError").textContent="";resetQuoteForm("transport");renderIntelligence();};
  $("lodgingQuoteForm").onsubmit=e=>{e.preventDefault();const option=lodgingFromForm(),v=T.validateLodgingOption(option);if(!v.valid){$("lodgingFormError").textContent=v.errors.join(" ");return;}const index=trip.lodging_options.findIndex(x=>x.id===option.id);if(index<0)trip.lodging_options.push(option);else trip.lodging_options[index]=option;$("lodgingFormError").textContent="";resetQuoteForm("lodging");renderIntelligence();};
  $("cancelTransportEdit").onclick=()=>resetQuoteForm("transport");$("cancelLodgingEdit").onclick=()=>resetQuoteForm("lodging");
  feeRows(); renderIntelligence(); resetQuoteForm("transport"); showStep(0);
})();
