(function () {
  "use strict";
  const B = window.SuitcaseBrain, form = document.getElementById("trip-intake"); if (!B || !form) return;
  const $ = id => document.getElementById(id), money = n => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(Number(n) || 0);
  let trip = B.createTrip(), step = 0;
  const steps = [...document.querySelectorAll(".planner-step")];
  const escape = value => String(value ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const value = id => $(id)?.value.trim() || "", number = id => Number($(id)?.value || 0), checked = id => !!$(id)?.checked;
  function showStep(index) { step = Math.max(0, Math.min(steps.length - 1, index)); steps.forEach((el, i) => { el.hidden = i !== step; }); $("stepLabel").textContent = `Step ${step + 1} of ${steps.length}`; $("prevStep").hidden = step === 0; $("nextStep").hidden = step === steps.length - 1; steps[step].querySelector("input, select, textarea, button")?.focus(); }
  function collect() {
    trip.updated_at = new Date().toISOString(); trip.identity = { title: value("tripTitle"), purpose: value("purpose"), vibe: value("vibe") };
    trip.origin = value("origin"); trip.destination = value("destination"); trip.destination_unknown = checked("flexDestination");
    trip.dates = { start: value("startDate"), end: value("endDate"), flexibility: value("dateFlexibility") };
    trip.budget = { total: number("budget"), reserve: number("reserve"), currency: value("currency") || "USD" };
    trip.traveler_count = Math.max(1, number("travelerCount"));
    trip.preferences = { lodging: value("lodging"), transport: value("transport"), walking: value("walking"), driving: value("driving"), interests: [...document.querySelectorAll('[name="interest"]:checked')].map(x => x.value), culture_community: value("culture"), food: value("food"), nightlife: value("nightlife"), outdoor_adventure: value("outdoor") };
    trip.needs = { pet_service_animal: value("petNeeds"), accessibility: value("accessibilityNeeds") };
    trip.modes = { business: checked("businessMode"), group: checked("groupMode"), safe_night_no_driving: checked("safeNightMode"), vendor_business_opportunity: checked("vendorMode") };
    trip.emergency = { scenario: value("emergencyScenario"), personal_safety: checked("personalSafety"), contacts: value("emergencyContacts"), documents_notes: value("documentsNotes"), booking_owners: value("bookingOwners") };
    return trip;
  }
  function travelerRow(t = {}) { return `<div class="editor-row traveler-row"><label>Label (optional)<input data-field="label" value="${escape(t.label)}"></label><label>Age / band<input data-field="age_band" value="${escape(t.age_band)}" placeholder="Adult, 14, senior"></label><label>Payment responsibility<input data-field="payment_responsibility" value="${escape(t.payment_responsibility)}" placeholder="Self / organizer"></label><label>Committed<input data-field="amount_committed" type="number" min="0" step=".01" value="${Number(t.amount_committed)||0}"></label><label>Paid<input data-field="amount_paid" type="number" min="0" step=".01" value="${Number(t.amount_paid)||0}"></label><label>Commitment state<select data-field="commitment_state">${B.COMMITMENT_STATES.map(s=>`<option ${s===(t.commitment_state||"INVITED")?"selected":""}>${s}</option>`).join("")}</select></label><button class="secondary remove-row" type="button">Remove</button></div>`; }
  function reservationRow(r = {}) { const fields=[["provider","Provider"],["description","Description"],["booking_price","Booking price","number"],["deposit_paid","Deposit paid","number"],["amount_paid_beyond_deposit","Other amount paid","number"],["remaining_balance","Remaining balance","number"],["paid_by","Paid by traveler/group"],["booking_date","Booking date","date"],["cancellation_deadline","Cancellation deadline","date"],["refundable_amount","Refundable amount","number"],["nonrefundable_amount","Nonrefundable amount","number"],["change_rebooking_fee","Change/rebooking fee","number"],["provider_cancellation_fee","Cancellation fee","number"],["provider_no_show_fee","No-show fee","number"],["credit_voucher_possibility","Credit/voucher possibility"],["confirmation_reference","Confirmation/reference"],["source","Policy source URL","url"],["notes","Notes"]]; return `<div class="editor-row reservation-row"><label>Category<select data-field="category">${B.RESERVATION_CATEGORIES.map(x=>`<option ${x===(r.category||"other")?"selected":""}>${x}</option>`).join("")}</select></label>${fields.map(([key,label,type="text"])=>`<label>${label}<input data-field="${key}" type="${type}" ${type==="number"?'min="0" step=".01"':''} value="${escape(r[key])}"></label>`).join("")}<label>Policy status<select data-field="policy_status"><option>UNKNOWN</option><option ${r.policy_status==="USER-ENTERED"?"selected":""}>USER-ENTERED</option><option ${r.policy_status==="VERIFIED"?"selected":""}>VERIFIED</option></select></label><button class="secondary remove-row" type="button">Remove</button></div>`; }
  function feeRows() { $("feeRows").innerHTML = trip.hidden_fees.map((f,i)=>`<div class="fee-row" data-index="${i}"><strong>${escape(f.category)}</strong><label>Status<select data-field="status">${B.FEE_STATUSES.map(s=>`<option ${s===f.status?"selected":""}>${s}</option>`).join("")}</select></label><label>Amount (blank if unknown)<input data-field="amount" type="number" min="0" step=".01" value="${f.amount==null?"":f.amount}"></label><label>Source / note<input data-field="source" value="${escape(f.source)}"></label></div>`).join(""); }
  function syncRows() { trip.travelers = [...document.querySelectorAll(".traveler-row")].map(row => Object.fromEntries([...row.querySelectorAll("[data-field]")].map(el=>[el.dataset.field, el.type==="number"?Number(el.value||0):el.value]))); trip.traveler_count = Math.max(trip.traveler_count, trip.travelers.length || 1); trip.reservations = [...document.querySelectorAll(".reservation-row")].map(row => Object.fromEntries([...row.querySelectorAll("[data-field]")].map(el=>[el.dataset.field, el.type==="number"?Number(el.value||0):el.value]))); [...document.querySelectorAll(".fee-row")].forEach(row=>{ const f=trip.hidden_fees[Number(row.dataset.index)]; row.querySelectorAll("[data-field]").forEach(el=>f[el.dataset.field]=el.dataset.field==="amount"?(el.value===""?null:Number(el.value)):el.value); }); }
  function renderBlueprint() { collect(); syncRows(); const valid=B.validateTrip(trip); if(!valid.valid){$("planError").textContent=valid.errors.join(" "); return;} $("planError").textContent=""; const b=B.budgetMetrics(trip), c=B.cancellationExposure(trip.reservations), fees=B.hiddenFeeMetrics(trip.hidden_fees); const one=B.dropoutScenario(trip,1), two=B.dropoutScenario(trip,2), unpaid=B.dropoutScenario(trip,0,true,true); const special=Object.entries(trip.modes).filter(([,on])=>on).map(([name])=>name.replaceAll("_"," ")).join(", ")||"None selected";
    $("blueprintSummary").innerHTML=[["TRIP TYPE",trip.identity.purpose||"Not set"],["GROUP",`${trip.traveler_count} planned · ${b.committed} committed · ${b.funded} funded`],["DATES",trip.dates.start?`${trip.dates.start} → ${trip.dates.end||"open"} (${trip.dates.flexibility})`:"Not set"],["DESTINATION",trip.destination_unknown?"Find me somewhere":trip.destination||"Not set"],["BUDGET",money(b.total)],["RESERVE",money(b.reserve)],["FUNDED AMOUNT",money(b.fundedAmount)],["FUNDING GAP",money(b.unfundedGap)],["PER-PERSON SHARE",money(b.plannedShare)],["DROPOUT EXPOSURE",money(one.totalFundingShortage)],["TRANSPORTATION",trip.preferences.transport],["LODGING",trip.preferences.lodging],["INTERESTS",trip.preferences.interests.join(", ")||"None selected"],["SPECIAL MODES",special]].map(([a,v])=>`<div><span>${escape(a)}</span><strong>${escape(v)}</strong></div>`).join("");
    $("dropoutResults").innerHTML=[["1 person drops",one],["2 people drop",two],["One unpaid traveler never pays",unpaid]].map(([label,x])=>`<tr><th>${label}</th><td>${money(x.currentShare)}</td><td>${x.remaining?money(x.newShare):"No travelers remain"}</td><td>${money(x.increasePerRemaining)}</td><td>${money(x.totalFundingShortage)}</td></tr>`).join("");
    $("cancelResults").innerHTML=[["Total booked value",c.totalBookedValue],["Total already paid",c.totalAlreadyPaid],["Estimated recoverable",c.estimatedRecoverable],["Estimated nonrefundable exposure",c.estimatedNonrefundable],["Estimated change/cancellation fees",c.estimatedFees],["Net estimated loss",c.netEstimatedLoss]].map(([k,v])=>`<div><span>${k}</span><strong>${money(v)}</strong></div>`).join("")+`<div><span>Credits / vouchers</span><strong>${escape(c.creditsVouchers.join(", ")||"UNKNOWN")}</strong></div><p class="source-note">${c.unknownPolicies} reservation policy record(s) are UNKNOWN. No provider rule was invented.</p>`;
    $("feeSummary").textContent=`${money(fees.total)} in entered/known/verified fees · ${fees.unknown} unknown item(s). Unknown fees are not silently priced.`;
    $("resilienceCards").innerHTML=B.resilience(trip).map(x=>`<article class="status-card status-${x.status.toLowerCase()}"><span>${x.status}</span><h4>${escape(x.label)}</h4><p>${escape(x.reason)}</p></article>`).join("");
    $("planResults").hidden=false; window.dispatchEvent(new CustomEvent("suitcasebrain:blueprint",{detail:trip})); $("planResults").scrollIntoView({behavior:matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth"});
  }
  function populate(t) { trip=t; const set=(id,v)=>{if($(id))$(id).value=v??""},check=(id,v)=>{if($(id))$(id).checked=!!v}; set("tripTitle",t.identity.title);set("purpose",t.identity.purpose);set("vibe",t.identity.vibe);set("origin",t.origin);set("destination",t.destination);check("flexDestination",t.destination_unknown);set("startDate",t.dates.start);set("endDate",t.dates.end);set("dateFlexibility",t.dates.flexibility);set("budget",t.budget.total);set("reserve",t.budget.reserve);set("currency",t.budget.currency);set("travelerCount",t.traveler_count);["lodging","transport","walking","driving"].forEach(k=>set(k,t.preferences[k]));set("culture",t.preferences.culture_community);set("food",t.preferences.food);set("nightlife",t.preferences.nightlife);set("outdoor",t.preferences.outdoor_adventure);set("petNeeds",t.needs.pet_service_animal);set("accessibilityNeeds",t.needs.accessibility);Object.keys(t.modes).forEach(k=>check({business:"businessMode",group:"groupMode",safe_night_no_driving:"safeNightMode",vendor_business_opportunity:"vendorMode"}[k],t.modes[k]));document.querySelectorAll('[name="interest"]').forEach(el=>el.checked=t.preferences.interests.includes(el.value));set("emergencyScenario",t.emergency.scenario);check("personalSafety",t.emergency.personal_safety);set("emergencyContacts",t.emergency.contacts);set("documentsNotes",t.emergency.documents_notes);set("bookingOwners",t.emergency.booking_owners);$("travelerRows").innerHTML=t.travelers.map(travelerRow).join("");$("reservationRows").innerHTML=t.reservations.map(reservationRow).join("");feeRows();showStep(0); }
  $("nextStep").onclick=()=>showStep(step+1); $("prevStep").onclick=()=>showStep(step-1); form.onsubmit=e=>{e.preventDefault();renderBlueprint();};
  $("addTraveler").onclick=()=>$("travelerRows").insertAdjacentHTML("beforeend",travelerRow()); $("addReservation").onclick=()=>$("reservationRows").insertAdjacentHTML("beforeend",reservationRow());
  document.addEventListener("click",e=>{if(e.target.matches(".remove-row"))e.target.closest(".editor-row").remove();});
  $("saveTrip").onclick=()=>{collect();syncRows();const v=B.validateTrip(trip);if(!v.valid)return alert(v.errors.join("\n"));localStorage.setItem(B.STORAGE_KEY,JSON.stringify(trip));$("persistenceStatus").textContent="Trip saved in this browser.";};
  $("loadTrip").onclick=()=>{try{const raw=localStorage.getItem(B.STORAGE_KEY);if(!raw)throw Error("No saved trip found in this browser.");const t=JSON.parse(raw),v=B.validateTrip(t);if(!v.valid)throw Error(v.errors.join(" "));populate(t);$("persistenceStatus").textContent="Saved trip loaded.";}catch(e){$("persistenceStatus").textContent=e.message;}};
  $("startOver").onclick=()=>{if(!confirm("Start over? The saved copy remains until you save again."))return;populate(B.createTrip());$("planResults").hidden=true;$("persistenceStatus").textContent="Started a new local trip.";};
  $("exportTrip").onclick=()=>{collect();syncRows();const blob=new Blob([JSON.stringify(trip,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="suitcase-brain-trip.json";a.click();URL.revokeObjectURL(a.href);};
  $("importTrip").onchange=async e=>{try{const t=JSON.parse(await e.target.files[0].text()),v=B.validateTrip(t);if(!v.valid)throw Error(v.errors.join(" "));populate(t);$("persistenceStatus").textContent="Validated trip imported. Save it to retain it in this browser.";}catch(err){$("persistenceStatus").textContent=`Import rejected: ${err.message}`;}e.target.value="";};
  $("emergencyToggle").onclick=()=>{$("emergencyPanel").hidden=!$("emergencyPanel").hidden;if(!$("emergencyPanel").hidden)$("emergencyScenario").focus();};
  feeRows(); showStep(0);
})();
